"""Added visibility column to user & instrument

Revision ID: cfa51c3c06de
Revises: 73c843f972c8
Create Date: 2025-04-09 14:51:51.728277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa51c3c06de'
down_revision: Union[str, None] = '73c843f972c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

visibility_enum = sa.Enum('ACTIVE', 'DELETED', name='visibilityenum')

def upgrade() -> None:
    """Upgrade schema."""
    visibility_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('visibility', visibility_enum, server_default=sa.text("'ACTIVE'"), nullable=False))
    op.add_column('users', sa.Column('visibility', visibility_enum, server_default=sa.text("'ACTIVE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'visibility')
    op.drop_column('instruments', 'visibility')
    visibility_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
