"""Blocked balance added to Balance table

Revision ID: d5252cbdeb4b
Revises: b250521ecbe4
Create Date: 2025-05-23 20:17:07.981842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5252cbdeb4b'
down_revision: Union[str, None] = 'b250521ecbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('blocked_amount', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'blocked_amount')
    # ### end Alembic commands ###
